apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx-repo
  namespace: ingress-nginx
spec:
  url: https://kubernetes.github.io/ingress-nginx
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.6
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-repo
  interval: 5m
  values:
    controller:
      publishService:
        enabled: true
      admissionWebhooks:
        enabled: true
      patch:
        enabled: true
  