apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack-repo
  namespace: cert-manager
spec:
  url: https://charts.jetstack.io
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: jetstack-repo
  values:
    installCRDs: true