apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notickets-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - notickets.ru
    secretName: notickets-tls
  rules:
  - host: notickets.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-nginx-controller
            port:
              number: 80
