apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: mariadb
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-cluster
  namespace: mariadb
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      version: 18.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    architecture: replication
    auth:
      rootPassword: 132465-Cs
      database: notickets
      username: lon8
      password: 132465-Cs
      replicationPassword: 132465-Cs
    primary:
      persistence:
        enabled: true
        size: 8Gi
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 500m
      configuration: |
        [mysqld]
        character-set-server = utf8mb4
        collation-server = utf8mb4_general_ci