apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: mariadb
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-cluster
  namespace: mariadb
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      version: 18.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    architecture: replication
    auth:
      rootPassword: 132465-Cs
      database: notickets
      username: lon8
      password: 132465-Cs
      replicationPassword: 132465-Cs
    primary:
      nodeSelector:
        environment: service
      tolerations:
      - key: service
        operator: Equal
        effect: NoSchedule
      persistence:
        enabled: true
        size: 6Gi
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 500m
      extraVolumes:
        - name: mariadb-config
          configMap:
            name: mariadb-config
      extraVolumeMounts:
        - name: mariadb-config
          mountPath: /opt/bitnami/mariadb/conf/my.cnf
          subPath: my.cnf
    secondary:
      persistence:
        enabled: true
        size: 4Gi
      resources:
        requests:
          memory: 512Mi
          cpu: 200m
        limits:
          memory: 1Gi
          cpu: 500m
      extraVolumes:
        - name: mariadb-config
          configMap:
            name: mariadb-config
      extraVolumeMounts:
        - name: mariadb-config
          mountPath: /opt/bitnami/mariadb/conf/my.cnf
          subPath: my.cnf