apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: mysqldb
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysqldb
spec:
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 11.1.11
  interval: 5m
  install:
    createNamespace: true
  values:
    auth:
      rootPassword: "132465-Cs"
      database: "notickets"
      username: "lon8"
      password: "132465-Cs"
    primary:
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 8Gi