apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-client-job
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-mariadb
        image: alpine:latest
        command: ["sh", "-c", "echo 'Checking DNS resolution...'; nslookup mariadb-cluster-primary.mariadb.svc.cluster.local; echo 'Checking MariaDB connection...'; while ! nc -z -v -w30 mariadb-cluster-primary.mariadb.svc.cluster.local 3306; do echo 'Waiting for MariaDB cluster to start...'; sleep 5; done; echo 'MariaDB is up!'"]
      containers:
      - name: mysql-client
        image: lon8/notickets_initdb:1.3
        command:
          - "/bin/sh"
          - "-c"
          - "mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < /docker-entrypoint-initdb.d/init.sql"
        env:
        - name: MYSQL_HOST
          value: "mariadb-cluster-primary.mariadb.svc.cluster.local"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "notickets"
        - name: MYSQL_USER
          value: "lon8"
        - name: MYSQL_PASSWORD
          value: "132465-Cs"
        livenessProbe:
          exec:
            command:
              - "/opt/bitnami/mariadb/bin/mariadb-admin"
              - "ping"
              - "--host=localhost"
              - "--user=root"
              - "--password=132465-Cs"
          initialDelaySeconds: 30
          periodSeconds: 10
      restartPolicy: Never