apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-initdb-cluster-job
spec:
  template:
    spec:
      # Добавляем ожидание доступности MariaDB кластера
      initContainers:
      - name: wait-for-mysqldb
        image: alpine:latest
        command: ["sh", "-c", "until nc -z -v -w30 mysql.mysqldb.svc.cluster.local 3306; do echo 'Waiting for MySQLDB cluster to start...'; sleep 5; done"]
      containers:
      - name: mysql-client
        image: lon8/notickets_initdb:1.4
        command:
          - "/bin/sh"
          - "-c"
          - "mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < /docker-entrypoint-initdb.d/init.sql"
        env:
        - name: MYSQL_HOST
          value: "mysql.mysqldb.svc.cluster.local"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "notickets"
        - name: MYSQL_USER
          value: "lon8"
        - name: MYSQL_PASSWORD
          value: "132465-Cs"
      restartPolicy: Never