apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: notickets
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # Используйте NodePort или ClusterIP в зависимости от вашей конфигурации
