apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx/namespace.yaml
  - ingress-nginx/helmrelease.yaml
  - cert-manager/namespace.yaml
  - cert-manager/helmrelease.yaml
